# Generated by Django 4.2.7 on 2024-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food/images/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
